baseURL = "http://localhost/hpc-scorpion/"
publishDir = "development"
buildDrafts = true
title = "Scorpion — HPC cluster of biology.tohoku.ac.jp"
defaultContentLanguage = "en"
noTimes = true
disableKinds = ["RSS"]

[author]
name = "Watal M. Iwasaki"

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions]
strikethrough = false

[markup.highlight]
noClasses = false

[module]
workspace = "hugo.work"
[[module.imports]]
path = "github.com/heavywatal/hugo-theme-nonblog"

[params]
logo_src = "logo.png"
logo_alt = "logo.png"
theme_color = "#400E82"
